import { ContentData } from '../types';

export interface PortfolioSummaryOptions {
  maxProjects?: number;
  maxProjectTech?: number;
  maxStoryLines?: number;
  maxSoftSkills?: number;
  maxEducation?: number;
  maxTimelineSteps?: number;
  maxFooterLinks?: number;
}

const uniq = (items: string[]) => {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const raw of items) {
    const v = (raw || '').trim();
    if (!v) continue;
    const key = v.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(v);
  }
  return out;
};

/**
 * Deterministic portfolio summary (SOURCE OF TRUTH).
 * This is NOT generated by the model; it's built from `data/content.ts`.
 */
export function buildDeterministicPortfolioSummary(
  content: ContentData,
  options?: PortfolioSummaryOptions
): {
  factsBlock: string;
  allowedTech: string[];
} {
  // Defaults are intentionally "all" so the assistant can see full portfolio detail.
  // Callers can cap these to control token budget.
  const maxProjects = options?.maxProjects ?? Number.POSITIVE_INFINITY;
  const maxProjectTech = options?.maxProjectTech ?? Number.POSITIVE_INFINITY;
  const maxStoryLines = options?.maxStoryLines ?? Number.POSITIVE_INFINITY;
  const maxSoftSkills = options?.maxSoftSkills ?? Number.POSITIVE_INFINITY;
  const maxEducation = options?.maxEducation ?? Number.POSITIVE_INFINITY;
  const maxTimelineSteps = options?.maxTimelineSteps ?? Number.POSITIVE_INFINITY;
  const maxFooterLinks = options?.maxFooterLinks ?? Number.POSITIVE_INFINITY;

  const name = content.hero?.name ?? 'Evi Nur Hidayah';
  const role = content.hero?.role ?? 'System Analyst';
  const tagline = content.hero?.tagline ?? '';

  const aboutTitle = content.about?.title ?? '';
  const storyTitle = content.about?.storyTitle ?? '';
  const storyLines = Array.isArray(content.about?.story)
    ? content.about.story.slice(0, Math.max(0, maxStoryLines))
    : [];

  const experience = Array.isArray(content.about?.experience)
    ? content.about.experience
        .map((e) => `- ${e.role} — ${e.company} (${e.period})${e.description ? ` — ${e.description}` : ''}`)
        .join('\n')
    : '';

  const softSkills = Array.isArray(content.about?.softSkills)
    ? content.about.softSkills
        .slice(0, Math.max(0, maxSoftSkills))
        .map((s) => `- ${s.title}${s.desc ? `: ${s.desc}` : ''}`)
        .join('\n')
    : '';

  const education = Array.isArray(content.about?.education)
    ? content.about.education
        .slice(0, Math.max(0, maxEducation))
        .map((e) => `- ${e.degree} — ${e.school} (${e.year})`)
        .join('\n')
    : '';

  const techStack = content.about?.techStack;
  const techModeling = techStack?.modeling?.skills ?? [];
  const techData = techStack?.data?.skills ?? [];
  const techTools = techStack?.tools?.skills ?? [];

  // Collect allowed technologies only from content.ts.
  const projectTech = (Array.isArray(content.projects?.items) ? content.projects.items : [])
    .flatMap((p) => (Array.isArray(p.technologies) ? p.technologies : []));

  const allowedTech = uniq([
    ...techModeling,
    ...techData,
    ...techTools,
    ...projectTech,
  ]);

  const projects = (Array.isArray(content.projects?.items) ? content.projects.items : [])
    .slice(0, maxProjects)
    .map((p) => {
      const tech = uniq(Array.isArray(p.technologies) ? p.technologies : []).slice(0, maxProjectTech);
      return [
        `- ${p.title} — ${p.role}`,
        p.description ? `  - Ringkas: ${p.description}` : '',
        p.challenge ? `  - Challenge: ${p.challenge}` : '',
        p.solution ? `  - Solution: ${p.solution}` : '',
        tech.length ? `  - Tech (from content.ts): ${tech.join(', ')}` : '',
        Array.isArray(p.results) && p.results.length
          ? `  - Results: ${p.results.slice(0, 5).join(' | ')}`
          : '',
      ].filter(Boolean).join('\n');
    })
    .join('\n');

  const timelineTitle = content.timeline?.title ?? '';
  const timelineSteps = Array.isArray(content.timeline?.steps)
    ? content.timeline.steps
        .slice(0, Math.max(0, maxTimelineSteps))
        .map((s) => `- ${s.title}: ${s.description}`)
        .join('\n')
    : '';

  const footer = content.footer;
  const footerBrand = footer?.brandName ?? '';
  const footerMission = footer?.mission ?? '';
  const footerCoordinates = Array.isArray(footer?.coordinates)
    ? footer!.coordinates
        .slice(0, Math.max(0, maxFooterLinks))
        .map((c) => `- ${c.label}: ${c.href}`)
        .join('\n')
    : '';
  const footerSocials = Array.isArray(footer?.socials)
    ? footer!.socials
        .slice(0, Math.max(0, maxFooterLinks))
        .map((s) => `- ${s.label}: ${s.href}`)
        .join('\n')
    : '';

  const cvUrl = content.cv?.url ?? '';
  const cvFilename = content.cv?.filename ?? '';

  const factsBlock = [
    `**SOURCE OF TRUTH (content.ts)**`,
    `Name: ${name}`,
    `Primary Role: ${role}`,
    tagline ? `Tagline: ${tagline}` : '',
    '',
    aboutTitle ? `**About (${aboutTitle}):**` : '**About:**',
    storyTitle ? `Story Title: ${storyTitle}` : '',
    storyLines.length ? storyLines.map((s) => `- ${s}`).join('\n') : '',
    '',
    experience ? `**Work Experience:**\n${experience}` : '',
    '',
    softSkills ? `**Soft Skills:**\n${softSkills}` : '',
    '',
    education ? `**Education:**\n${education}` : '',
    '',
    `**Tech Stack (from content.ts):**`,
    techModeling.length ? `- Modeling & Architecture: ${techModeling.join(', ')}` : '- Modeling & Architecture: (not provided)',
    techData.length ? `- Data & Development: ${techData.join(', ')}` : '- Data & Development: (not provided)',
    techTools.length ? `- Management & Tools: ${techTools.join(', ')}` : '- Management & Tools: (not provided)',
    '',
    projects ? `**Projects (subset):**\n${projects}` : '',
    '',
    timelineTitle ? `**Timeline / Process (${timelineTitle}):**` : '**Timeline / Process:**',
    timelineSteps ? timelineSteps : '',
    '',
    footerBrand ? `**Footer:**\nBrand: ${footerBrand}` : (footerMission || footerCoordinates || footerSocials ? '**Footer:**' : ''),
    footerMission ? `Mission: ${footerMission}` : '',
    footerCoordinates ? `Coordinates:\n${footerCoordinates}` : '',
    footerSocials ? `Socials:\n${footerSocials}` : '',
    '',
    (cvUrl || cvFilename) ? '**CV:**' : '',
    cvFilename ? `Filename: ${cvFilename}` : '',
    cvUrl ? `URL: ${cvUrl}` : '',
  ].filter(Boolean).join('\n');

  return { factsBlock, allowedTech };
}
