import { ContentData } from '../types';

export interface PortfolioSummaryOptions {
  maxProjects?: number;
  maxProjectTech?: number;
  maxStoryLines?: number;
  maxSoftSkills?: number;
  maxEducation?: number;
  maxTimelineSteps?: number;
  maxFooterLinks?: number;
}

export type RoutedPortfolioMode =
  | 'base'
  | 'all-projects'
  | 'project'
  | 'education'
  | 'soft-skills'
  | 'timeline'
  | 'contact'
  | 'experience'
  | 'tech-stack';

const uniq = (items: string[]) => {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const raw of items) {
    const v = (raw || '').trim();
    if (!v) continue;
    const key = v.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(v);
  }
  return out;
};

/**
 * Deterministic portfolio summary (SOURCE OF TRUTH).
 * This is NOT generated by the model; it's built from `data/content.ts`.
 */
export function buildDeterministicPortfolioSummary(
  content: ContentData,
  options?: PortfolioSummaryOptions
): {
  factsBlock: string;
  allowedTech: string[];
} {
  // Defaults are intentionally "all" so the assistant can see full portfolio detail.
  // Callers can cap these to control token budget.
  const maxProjects = options?.maxProjects ?? Number.POSITIVE_INFINITY;
  const maxProjectTech = options?.maxProjectTech ?? Number.POSITIVE_INFINITY;
  const maxStoryLines = options?.maxStoryLines ?? Number.POSITIVE_INFINITY;
  const maxSoftSkills = options?.maxSoftSkills ?? Number.POSITIVE_INFINITY;
  const maxEducation = options?.maxEducation ?? Number.POSITIVE_INFINITY;
  const maxTimelineSteps = options?.maxTimelineSteps ?? Number.POSITIVE_INFINITY;
  const maxFooterLinks = options?.maxFooterLinks ?? Number.POSITIVE_INFINITY;

  const name = content.hero?.name ?? 'Evi Nur Hidayah';
  const role = content.hero?.role ?? 'System Analyst';
  const tagline = content.hero?.tagline ?? '';

  const aboutTitle = content.about?.title ?? '';
  const storyTitle = content.about?.storyTitle ?? '';
  const storyLines = Array.isArray(content.about?.story)
    ? content.about.story.slice(0, Math.max(0, maxStoryLines))
    : [];

  const experience = Array.isArray(content.about?.experience)
    ? content.about.experience
      .map((e) => `- ${e.role} — ${e.company} (${e.period})${e.description ? ` — ${e.description}` : ''}`)
      .join('\n')
    : '';

  const softSkills = Array.isArray(content.about?.softSkills)
    ? content.about.softSkills
      .slice(0, Math.max(0, maxSoftSkills))
      .map((s) => `- ${s.title}${s.desc ? `: ${s.desc}` : ''}`)
      .join('\n')
    : '';

  const education = Array.isArray(content.about?.education)
    ? content.about.education
      .slice(0, Math.max(0, maxEducation))
      .map((e) => `- ${e.degree} — ${e.school} (${e.year})`)
      .join('\n')
    : '';

  const techStack = content.about?.techStack;
  const techModeling = techStack?.modeling?.skills ?? [];
  const techData = techStack?.data?.skills ?? [];
  const techTools = techStack?.tools?.skills ?? [];

  // Collect allowed technologies only from content.ts.
  const projectTech = (Array.isArray(content.projects?.items) ? content.projects.items : [])
    .flatMap((p) => (Array.isArray(p.technologies) ? p.technologies : []));

  const allowedTech = uniq([
    ...techModeling,
    ...techData,
    ...techTools,
    ...projectTech,
  ]);

  const projects = (Array.isArray(content.projects?.items) ? content.projects.items : [])
    .slice(0, maxProjects)
    .map((p) => {
      const tech = uniq(Array.isArray(p.technologies) ? p.technologies : []).slice(0, maxProjectTech);
      return [
        `- ${p.title} — ${p.role}`,
        p.description ? `  - Ringkas: ${p.description}` : '',
        p.challenge ? `  - Challenge: ${p.challenge}` : '',
        p.solution ? `  - Solution: ${p.solution}` : '',
        tech.length ? `  - Tech (from content.ts): ${tech.join(', ')}` : '',
        Array.isArray(p.results) && p.results.length
          ? `  - Results: ${p.results.slice(0, 5).join(' | ')}`
          : '',
      ].filter(Boolean).join('\n');
    })
    .join('\n');

  const timelineTitle = content.timeline?.title ?? '';
  const timelineSteps = Array.isArray(content.timeline?.steps)
    ? content.timeline.steps
      .slice(0, Math.max(0, maxTimelineSteps))
      .map((s) => `- ${s.title}: ${s.description}`)
      .join('\n')
    : '';

  const footer = content.footer;
  const footerBrand = footer?.brandName ?? '';
  const footerMission = footer?.mission ?? '';
  const footerCoordinates = Array.isArray(footer?.coordinates)
    ? footer!.coordinates
      .slice(0, Math.max(0, maxFooterLinks))
      .map((c) => `- ${c.label}: ${c.href}`)
      .join('\n')
    : '';
  const footerSocials = Array.isArray(footer?.socials)
    ? footer!.socials
      .slice(0, Math.max(0, maxFooterLinks))
      .map((s) => `- ${s.label}: ${s.href}`)
      .join('\n')
    : '';

  const cvUrl = content.cv?.url ?? '';
  const cvFilename = content.cv?.filename ?? '';

  const factsBlock = [
    `**SOURCE OF TRUTH (content.ts)**`,
    `Name: ${name}`,
    `Primary Role: ${role}`,
    tagline ? `Tagline: ${tagline}` : '',
    '',
    aboutTitle ? `**About (${aboutTitle}):**` : '**About:**',
    storyTitle ? `Story Title: ${storyTitle}` : '',
    storyLines.length ? storyLines.map((s) => `- ${s}`).join('\n') : '',
    '',
    experience ? `**Work Experience:**\n${experience}` : '',
    '',
    softSkills ? `**Soft Skills:**\n${softSkills}` : '',
    '',
    education ? `**Education:**\n${education}` : '',
    '',
    `**Tech Stack (from content.ts):**`,
    techModeling.length ? `- Modeling & Architecture: ${techModeling.join(', ')}` : '- Modeling & Architecture: (not provided)',
    techData.length ? `- Data & Development: ${techData.join(', ')}` : '- Data & Development: (not provided)',
    techTools.length ? `- Management & Tools: ${techTools.join(', ')}` : '- Management & Tools: (not provided)',
    '',
    projects ? `**Projects (subset):**\n${projects}` : '',
    '',
    timelineTitle ? `**Timeline / Process (${timelineTitle}):**` : '**Timeline / Process:**',
    timelineSteps ? timelineSteps : '',
    '',
    footerBrand ? `**Footer:**\nBrand: ${footerBrand}` : (footerMission || footerCoordinates || footerSocials ? '**Footer:**' : ''),
    footerMission ? `Mission: ${footerMission}` : '',
    footerCoordinates ? `Coordinates:\n${footerCoordinates}` : '',
    footerSocials ? `Socials:\n${footerSocials}` : '',
    '',
    (cvUrl || cvFilename) ? '**CV:**' : '',
    cvFilename ? `Filename: ${cvFilename}` : '',
    cvUrl ? `URL: ${cvUrl}` : '',
  ].filter(Boolean).join('\n');

  return { factsBlock, allowedTech };
}

const normalize = (s: string) => (s || '').toLowerCase().trim();

const pickProjectByTitleHint = (content: ContentData, userMessage: string) => {
  const msg = normalize(userMessage);
  const items = Array.isArray(content.projects?.items) ? content.projects!.items : [];
  if (!items.length) return null;

  // Try exact title match first
  for (const p of items) {
    const title = normalize(p.title || '');
    if (title && msg.includes(title)) return p;
  }

  // Common shorthand: remove spaces
  const compact = msg.replace(/\s+/g, '');
  for (const p of items) {
    const title = normalize(p.title || '').replace(/\s+/g, '');
    if (title && compact.includes(title)) return p;
  }

  return null;
};

export function detectRoutedPortfolioMode(content: ContentData, userMessage: string): RoutedPortfolioMode {
  const msg = normalize(userMessage);

  const asksAllProjects = /(semua\s+proyek|daftar\s+proyek|list\s+proyek|proyek\s+apa\s+saja)/i.test(msg);
  if (asksAllProjects) return 'all-projects';

  // If user mentions a known project title, go project mode.
  if (pickProjectByTitleHint(content, msg)) return 'project';

  if (/(pendidikan|kuliah|sekolah|education|sertif|cert|universitas|lulusan|alumni|gelar|degree|ijazah|diploma|sarjana|master|s1|s2|s3|kampus|academy|bootcamp|uty|yogyakarta)/i.test(msg)) return 'education';
  if (/(soft\s*skill|softskill|leadership|kepemimpinan|team|tim|komunikasi|communication|problem\s*solving|manajemen|management|kolaborasi|collaboration|adaptasi|adaptation|interpersonal|empati|empathy|kritis|critical\s*thinking)/i.test(msg)) return 'soft-skills';
  if (/(timeline|process|proses|tahapan|metode|workflow|cara\s*kerja|langkah|step|discovery|analysis|design|development|deployment|siklus|lifecycle|metodologi|methodology|sprint|agile)/i.test(msg)) return 'timeline';
  if (/(kontak|contact|linkedin|instagram|email|cv|resume|portofolio|portfolio|github|website|link|sosmed|social\s*media|hubungi|telp|wa|whatsapp|telegram|dm|pesan|message)/i.test(msg)) return 'contact';
  if (/(pengalaman|kerja|karir|career|experience|work|job|perusahaan|company|kantor|office|history|riwayat|jabatan|posisi|role|magang|intern|horus|libur\s*ngoding)/i.test(msg)) return 'experience';
  if (/(tech|teknologi|stack|bahasa|language|framework|database|tool|alat|skill|kemampuan|keahlian|modeling|architecture|data|development|management|uml|erd|bpmn|figma|sql|postgresql|bigquery|jira|clickup)/i.test(msg)) return 'tech-stack';

  return 'base';
}

/**
 * Token-saving router: builds a minimal, question-targeted facts block.
 * - Default 'base' is compact.
 * - Still deterministic + grounded to content.ts.
 */
export function buildRoutedPortfolioContext(
  content: ContentData,
  userMessage: string
): {
  mode: RoutedPortfolioMode;
  factsBlock: string;
  allowedTech: string[];
} {
  const { allowedTech } = buildDeterministicPortfolioSummary(content, {
    // allowedTech should include everything (for validation), but the factsBlock can be small.
    maxProjects: Number.POSITIVE_INFINITY,
    maxProjectTech: Number.POSITIVE_INFINITY,
    maxStoryLines: Number.POSITIVE_INFINITY,
    maxSoftSkills: Number.POSITIVE_INFINITY,
    maxEducation: Number.POSITIVE_INFINITY,
    maxTimelineSteps: Number.POSITIVE_INFINITY,
    maxFooterLinks: Number.POSITIVE_INFINITY,
  });

  const mode = detectRoutedPortfolioMode(content, userMessage);

  const name = content.hero?.name ?? 'Evi Nur Hidayah';
  const role = content.hero?.role ?? 'System Analyst';
  const tagline = content.hero?.tagline ?? '';

  const items = Array.isArray(content.projects?.items) ? content.projects!.items : [];

  // Compact base: identity + 1-2 story lines + tech stack headings + project titles.
  if (mode === 'base') {
    const story = Array.isArray(content.about?.story) ? content.about!.story.slice(0, 2) : [];
    const techStack = content.about?.techStack;
    const techModeling = techStack?.modeling?.skills ?? [];
    const techData = techStack?.data?.skills ?? [];
    const techTools = techStack?.tools?.skills ?? [];
    const projectTitles = items.map((p) => p.title).filter(Boolean);

    const factsBlock = [
      `**SOURCE OF TRUTH (content.ts)**`,
      `Name: ${name}`,
      `Primary Role: ${role}`,
      tagline ? `Tagline: ${tagline}` : '',
      '',
      story.length ? `**Story (ringkas):**\n${story.map((s) => `- ${s}`).join('\n')}` : '',
      '',
      `**Tech Stack (from content.ts):**`,
      techModeling.length ? `- Modeling & Architecture: ${techModeling.join(', ')}` : '',
      techData.length ? `- Data & Development: ${techData.join(', ')}` : '',
      techTools.length ? `- Management & Tools: ${techTools.join(', ')}` : '',
      '',
      projectTitles.length ? `**Project Titles:**\n${projectTitles.map((t) => `- ${t}`).join('\n')}` : '',
    ].filter(Boolean).join('\n');

    return { mode, factsBlock, allowedTech };
  }

  if (mode === 'all-projects') {
    const titles = items.map((p) => p.title).filter(Boolean);
    const factsBlock = [
      `**SOURCE OF TRUTH (content.ts)**`,
      `Name: ${name}`,
      `Primary Role: ${role}`,
      '',
      `**SEMUA PROYEK (judul persis dari content.ts):**`,
      titles.length ? titles.map((t) => `- ${t}`).join('\n') : '(tidak ada data proyek)',
    ].filter(Boolean).join('\n');
    return { mode, factsBlock, allowedTech };
  }

  if (mode === 'project') {
    const p = pickProjectByTitleHint(content, userMessage);
    const tech = uniq(Array.isArray(p?.technologies) ? p!.technologies : []);
    const factsBlock = [
      `**SOURCE OF TRUTH (content.ts)**`,
      `Project: ${p?.title ?? '(unknown)'}`,
      p?.role ? `Role: ${p.role}` : '',
      p?.description ? `Ringkas: ${p.description}` : '',
      p?.challenge ? `Challenge: ${p.challenge}` : '',
      p?.solution ? `Solution: ${p.solution}` : '',
      tech.length ? `Tech (from content.ts): ${tech.join(', ')}` : '',
      Array.isArray(p?.results) && p!.results.length ? `Results: ${p!.results.join(' | ')}` : '',
    ].filter(Boolean).join('\n');
    return { mode, factsBlock, allowedTech };
  }

  if (mode === 'education') {
    const ed = Array.isArray(content.about?.education) ? content.about!.education : [];
    const factsBlock = [
      `**SOURCE OF TRUTH (content.ts)**`,
      `Name: ${name}`,
      '',
      `**Education:**`,
      ed.length ? ed.map((e) => `- ${e.degree} — ${e.school} (${e.year})`).join('\n') : '(not provided)',
    ].filter(Boolean).join('\n');
    return { mode, factsBlock, allowedTech };
  }

  if (mode === 'soft-skills') {
    const ss = Array.isArray(content.about?.softSkills) ? content.about!.softSkills : [];
    const factsBlock = [
      `**SOURCE OF TRUTH (content.ts)**`,
      `Name: ${name}`,
      '',
      `**Soft Skills:**`,
      ss.length ? ss.map((s) => `- ${s.title}${s.desc ? `: ${s.desc}` : ''}`).join('\n') : '(not provided)',
    ].filter(Boolean).join('\n');
    return { mode, factsBlock, allowedTech };
  }

  if (mode === 'timeline') {
    const t = content.timeline;
    const steps = Array.isArray(t?.steps) ? t!.steps : [];
    const factsBlock = [
      `**SOURCE OF TRUTH (content.ts)**`,
      `Name: ${name}`,
      '',
      t?.title ? `**Timeline / Process (${t.title}):**` : '**Timeline / Process:**',
      steps.length ? steps.map((s) => `- ${s.title}: ${s.description}`).join('\n') : '(not provided)',
    ].filter(Boolean).join('\n');
    return { mode, factsBlock, allowedTech };
  }

  if (mode === 'experience') {
    const exp = Array.isArray(content.about?.experience) ? content.about!.experience : [];
    const factsBlock = [
      `**SOURCE OF TRUTH (content.ts)**`,
      `Name: ${name}`,
      '',
      `**Work Experience:**`,
      exp.length ? exp.map((e) => `- ${e.role} — ${e.company} (${e.period})${e.description ? ` — ${e.description}` : ''}`).join('\n') : '(not provided)',
    ].filter(Boolean).join('\n');
    return { mode, factsBlock, allowedTech };
  }

  if (mode === 'tech-stack') {
    const ts = content.about?.techStack;
    const techModeling = ts?.modeling?.skills ?? [];
    const techData = ts?.data?.skills ?? [];
    const techTools = ts?.tools?.skills ?? [];
    const factsBlock = [
      `**SOURCE OF TRUTH (content.ts)**`,
      `Name: ${name}`,
      '',
      `**Tech Stack (from content.ts):**`,
      techModeling.length ? `- Modeling & Architecture: ${techModeling.join(', ')}` : '',
      techData.length ? `- Data & Development: ${techData.join(', ')}` : '',
      techTools.length ? `- Management & Tools: ${techTools.join(', ')}` : '',
    ].filter(Boolean).join('\n');
    return { mode, factsBlock, allowedTech };
  }

  // contact
  const footer = content.footer;
  const socials = Array.isArray(footer?.socials) ? footer!.socials : [];
  const cv = content.cv;
  const factsBlock = [
    `**SOURCE OF TRUTH (content.ts)**`,
    `Name: ${name}`,
    '',
    `**Contact / Links:**`,
    socials.length ? socials.map((s) => `- ${s.label}: ${s.href}`).join('\n') : '',
    cv?.url ? `- CV: ${cv.url}` : '',
  ].filter(Boolean).join('\n');

  return { mode: 'contact', factsBlock, allowedTech };
}
